import React from 'react';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-8">
      <h1 className="text-3xl font-bold mb-6 text-center">Terms and Conditions of Service</h1>
      <p className="text-sm text-gray-500 mb-8 text-center">
        Last Updated: October 20, 2025
      </p>

      <p className="mb-6">
        Welcome to <span>PatchMyResume</span> (the "Service"), a tool designed to help you tailor your resume using Google Gemini AI. These Terms and Conditions ("Terms") govern your access to and use of the Service. By accessing or using the Service, you agree to be bound by these Terms.
      </p>

      {/* --- 1. Acceptance of Terms --- */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">1. Acceptance of Terms</h2>
        <p>
          By creating an account, logging in, or using any part of the Service, you confirm that you are over 18 and agree to these Terms. If you disagree with any part of the terms, you must not use the Service.
        </p>
      </section>

      {/* --- 2. User Responsibilities & API Key Use --- */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">2. User Responsibilities & API Key Use</h2>
        
        <h3 className="text-xl font-medium mb-3">A. Your API Key</h3>
        <ul className="list-disc list-inside ml-4 space-y-2">
          <li>
            <span>User Ownership:</span> The Service requires you to provide your own <span>Google Gemini API Key</span>. You acknowledge and agree that this key belongs to you, and you are solely responsible for its security, usage, and any associated costs incurred from the use of the Google Gemini API.
          </li>
          <li>
            <span>Usage Compliance:</span> You agree to use the API key and the Service in compliance with Google's own terms of service for the Gemini API.
          </li>
          <li>
            <span>Security:</span> You must not share your account login credentials. While the Service takes measures to hash your key (as described in the Privacy Policy), you are responsible for maintaining the confidentiality of your API key outside of the Service.
          </li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">B. Prohibited Conduct</h3>
        <p>
          You agree not to use the Service to:
        </p>
        <ul className="list-disc list-inside ml-4 space-y-2">
          <li>Generate resumes for any illegal or fraudulent purposes.</li>
          <li>Attempt to reverse engineer, disassemble, or derive the source code of the Service.</li>
          <li>Overload, attack, or impose an unreasonable burden on our infrastructure (Appwrite, Vercel, etc.).</li>
          <li>Introduce malicious or technologically harmful material.</li>
        </ul>
      </section>

      {/* --- 3. Intellectual Property and Content --- */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">3. Intellectual Property and Content</h2>
        
        <h3 className="text-xl font-medium mb-3">A. User Content (Your Resume Data)</h3>
        <p>
          You retain all ownership rights to the <span>Resume Data</span> you input into the Service. By using the Service, you grant us a limited, royalty-free license to use this data solely for the purpose of providing and improving the Service (e.g., generating AI suggestions, formatting PDFs).
        </p>
        
        <h3 className="text-xl font-medium mt-6 mb-3">B. Service Content</h3>
        <p>
          All content, features, and functionality provided by the Service (including the underlying code, design, and logos, excluding User Content) are owned by the project creator and protected by intellectual property laws.
        </p>
      </section>

      {/* --- 4. Disclaimers and Limitation of Liability --- */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">4. Disclaimers and Limitation of Liability</h2>
        
        <h3 className="text-xl font-medium mb-3">A. AI-Generated Content Disclaimer</h3>
        <p>
          The resume suggestions provided by the Service are generated by a third-party AI (Google Gemini). The Service does not guarantee the accuracy, completeness, or effectiveness of these suggestions. <span>You are solely responsible for reviewing and approving all content</span> before applying it to your resume and submitting it to potential employers.
        </p>
        
        <h3 className="text-xl font-medium mt-6 mb-3">B. "As Is" Basis</h3>
        <p>
          The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, expressed or implied, regarding the operation or availability of the Service, or the outcome of any job application submitted using a tailored resume.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">C. Limitation of Liability</h3>
        <p>
          In no event shall the project creator or maintainers be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from: (i) your access to or use of the Service; (ii) any conduct or content of any third party; or (iii) any tailored content or suggestions provided by the AI.
        </p>
      </section>

      {/* --- 5. Termination --- */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">5. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms. You may cease using the Service at any time. All provisions of the Terms which, by their nature, should survive termination shall survive termination, including ownership provisions, warranty disclaimers, and limitations of liability.
        </p>
      </section>

      {/* --- 6. Governing Law --- */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">6. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of the jurisdiction where the project creator resides, without regard to its conflict of law provisions.
        </p>
      </section>
      
      {/* --- 7. Changes to Terms --- */}
      <section>
        <h2 className="text-2xl font-semibold mb-4 border-b pb-2">7. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
        </p>
      </section>

    </div>
  );
};

export default TermsAndConditions;